CREATE TABLE workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID UNIQUE NOT NULL,
    worker_name VARCHAR(255) NOT NULL,
    instance_id VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_heartbeat_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL
);

CREATE TABLE worker_capabilities (
    worker_id BIGINT NOT NULL,
    capability VARCHAR(100) NOT NULL,
    PRIMARY KEY (worker_id, capability),
    CONSTRAINT fk_worker_capabilities_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE
);

CREATE TABLE execution_leases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_public_id UUID UNIQUE NOT NULL,
    worker_public_id UUID NOT NULL,
    lease_token VARCHAR(255) NOT NULL,
    lease_version BIGINT NOT NULL,
    leased_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lease_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL
);

CREATE INDEX idx_execution_leases_expires ON execution_leases (lease_expires_at);
