package com.flowforge.api.service;

import com.flowforge.api.BasePersistenceIT;
import com.flowforge.api.dto.InternalExecutionFinalizeRequest;
import com.flowforge.api.model.*;
import com.flowforge.api.repository.*;
import com.flowforge.api.shared.identity.PublicIdGenerator;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.time.Clock;
import java.time.Instant;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@AutoConfigureMockMvc
public class ExecutionFinalizationIT extends BasePersistenceIT {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private TenantRepository tenantRepository;

    @Autowired
    private ProjectRepository projectRepository;

    @Autowired
    private JobRepository jobRepository;

    @Autowired
    private ExecutionRepository executionRepository;

    @Autowired
    private ExecutionAttemptRepository attemptRepository;

    @Autowired
    private OutboxEventRepository outboxEventRepository;

    @Autowired
    private PublicIdGenerator publicIdGenerator;

    @Autowired
    private Clock clock;

    @Autowired
    private org.springframework.jdbc.core.JdbcTemplate jdbcTemplate;

    private User user;
    private Tenant tenant;
    private Project project;
    private Job job;
    private Execution execution;
    private ExecutionAttempt attempt;
    private String leaseToken;

    @BeforeEach
    public void setupData() {
        // Create schema tables for workers and leases if not present (simulate Flyway V8)
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS workers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id UUID UNIQUE, worker_name VARCHAR(255), instance_id VARCHAR(255), status VARCHAR(50), registered_at TIMESTAMP WITH TIME ZONE, last_heartbeat_at TIMESTAMP WITH TIME ZONE, version BIGINT)");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS execution_leases (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, execution_public_id UUID UNIQUE NOT NULL, worker_public_id UUID NOT NULL, lease_token VARCHAR(255) NOT NULL, lease_version BIGINT NOT NULL, leased_at TIMESTAMP WITH TIME ZONE NOT NULL, lease_expires_at TIMESTAMP WITH TIME ZONE NOT NULL, version BIGINT NOT NULL)");
        jdbcTemplate.execute("DELETE FROM execution_leases");
        jdbcTemplate.execute("DELETE FROM workers");

        user = userRepository.save(new User(publicIdGenerator.generate(), "test-final@flowforge.com", "hash", UserStatus.ACTIVE));
        tenant = tenantRepository.save(new Tenant(publicIdGenerator.generate(), "Test Tenant", TenantStatus.ACTIVE, user.getPublicId()));
        project = projectRepository.save(new Project(publicIdGenerator.generate(), tenant, "Test Project", ProjectStatus.ACTIVE, user.getPublicId()));
        job = jobRepository.save(new Job(
                publicIdGenerator.generate(), project, "Test Job", "Desc", true,
                JobHttpMethod.GET, "http://target.com", null, null, 10,
                null, null, null, JobScheduleType.MANUAL, null, JobStatus.ACTIVE, user.getPublicId()
        ));
        
        execution = new Execution(publicIdGenerator.generate(), job, ExecutionTriggerType.MANUAL, "user", clock.instant(), 3);
        execution.start(clock.instant()); // Transition to RUNNING
        execution = executionRepository.save(execution);

        attempt = new ExecutionAttempt(publicIdGenerator.generate(), 1, AttemptStatus.PENDING, clock.instant());
        attempt.start("worker-1", clock.instant());
        execution.addAttempt(attempt);
        attempt = attemptRepository.save(attempt);

        leaseToken = UUID.randomUUID().toString();
        // Insert lease into DB manually
        jdbcTemplate.update(
                "INSERT INTO execution_leases (execution_public_id, worker_public_id, lease_token, lease_version, leased_at, lease_expires_at, version) VALUES (?, ?, ?, ?, ?, ?, ?)",
                execution.getPublicId(),
                UUID.randomUUID(),
                leaseToken,
                1L,
                clock.instant(),
                clock.instant().plusSeconds(60),
                0L
        );
    }

    @Test
    public void testSuccessfulFinalization() throws Exception {
        InternalExecutionFinalizeRequest request = new InternalExecutionFinalizeRequest(
                leaseToken,
                clock.instant(),
                clock.instant().plusMillis(500),
                200,
                512L,
                false,
                "application/json",
                null
        );

        mockMvc.perform(post("/internal/v1/executions/" + execution.getPublicId() + "/finalize")
                        .header("X-Internal-Service-Token", "default-internal-token-secret-key-12345")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());

        // Verify Execution status is SUCCEEDED
        Execution updatedExec = executionRepository.findByPublicId(execution.getPublicId()).orElseThrow();
        assertThat(updatedExec.getCurrentStatus()).isEqualTo(ExecutionStatus.SUCCEEDED);

        // Verify ExecutionAttempt status is SUCCEEDED with HTTP status
        ExecutionAttempt updatedAttempt = attemptRepository.findById(attempt.getId()).orElseThrow();
        assertThat(updatedAttempt.getStatus()).isEqualTo(AttemptStatus.SUCCEEDED);
        assertThat(updatedAttempt.getHttpStatus()).isEqualTo(200);
        assertThat(updatedAttempt.getResponseSize()).isEqualTo(512L);
        assertThat(updatedAttempt.getBodyTruncated()).isFalse();

        // Verify lease was deleted/released
        Integer leaseCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM execution_leases WHERE execution_public_id = ?",
                Integer.class,
                execution.getPublicId()
        );
        assertThat(leaseCount).isEqualTo(0);

        // Verify EXECUTION_COMPLETED outbox event version 2
        OutboxEvent event = outboxEventRepository.findAll().stream()
                .filter(e -> e.getEventType().equals("EXECUTION_COMPLETED"))
                .findFirst().orElseThrow();
        assertThat(event.getPayloadVersion()).isEqualTo(2);
        assertThat(event.getPayload()).contains("SUCCEEDED");
    }

    @Test
    public void testFailedFinalizationWithNetworkError() throws Exception {
        InternalExecutionFinalizeRequest request = new InternalExecutionFinalizeRequest(
                leaseToken,
                clock.instant(),
                clock.instant().plusMillis(100),
                null,
                0L,
                false,
                null,
                "CONNECTION_TIMEOUT"
        );

        mockMvc.perform(post("/internal/v1/executions/" + execution.getPublicId() + "/finalize")
                        .header("X-Internal-Service-Token", "default-internal-token-secret-key-12345")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());

        Execution updatedExec = executionRepository.findByPublicId(execution.getPublicId()).orElseThrow();
        assertThat(updatedExec.getCurrentStatus()).isEqualTo(ExecutionStatus.FAILED);

        ExecutionAttempt updatedAttempt = attemptRepository.findById(attempt.getId()).orElseThrow();
        assertThat(updatedAttempt.getStatus()).isEqualTo(AttemptStatus.FAILED);
        assertThat(updatedAttempt.getNetworkError()).isEqualTo("CONNECTION_TIMEOUT");
        assertThat(updatedAttempt.getErrorCategory()).isEqualTo("NETWORK_ERROR");
    }

    @Test
    public void testAuthenticationRequired() throws Exception {
        InternalExecutionFinalizeRequest request = new InternalExecutionFinalizeRequest(
                leaseToken,
                clock.instant(),
                clock.instant().plusMillis(500),
                200,
                512L,
                false,
                "application/json",
                null
        );

        // Call without header or with invalid token
        mockMvc.perform(post("/internal/v1/executions/" + execution.getPublicId() + "/finalize")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isUnauthorized());

        mockMvc.perform(post("/internal/v1/executions/" + execution.getPublicId() + "/finalize")
                        .header("X-Internal-Service-Token", "invalid-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isUnauthorized());
    }

    @Test
    public void testDuplicateFinalizationRejection() throws Exception {
        InternalExecutionFinalizeRequest request = new InternalExecutionFinalizeRequest(
                leaseToken,
                clock.instant(),
                clock.instant().plusMillis(500),
                200,
                512L,
                false,
                "application/json",
                null
        );

        // First finalization
        mockMvc.perform(post("/internal/v1/executions/" + execution.getPublicId() + "/finalize")
                        .header("X-Internal-Service-Token", "default-internal-token-secret-key-12345")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());

        // Second finalization on non-running execution (succeeded/failed state)
        mockMvc.perform(post("/internal/v1/executions/" + execution.getPublicId() + "/finalize")
                        .header("X-Internal-Service-Token", "default-internal-token-secret-key-12345")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isInternalServerError()); // IllegalStateException mapped to 500
    }

    @Test
    public void testRollbackGuarantees() throws Exception {
        // Intentionally trigger validation failure (which throws exception and rolls back)
        InternalExecutionFinalizeRequest request = new InternalExecutionFinalizeRequest(
                "invalid-lease-token",
                clock.instant(),
                clock.instant().plusMillis(500),
                200,
                512L,
                false,
                "application/json",
                null
        );

        mockMvc.perform(post("/internal/v1/executions/" + execution.getPublicId() + "/finalize")
                        .header("X-Internal-Service-Token", "default-internal-token-secret-key-12345")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest()); // InvalidRequestException maps to 400

        // Verify database rolled back: execution remains RUNNING
        Execution updatedExec = executionRepository.findByPublicId(execution.getPublicId()).orElseThrow();
        assertThat(updatedExec.getCurrentStatus()).isEqualTo(ExecutionStatus.RUNNING);

        // Attempt remains RUNNING
        ExecutionAttempt updatedAttempt = attemptRepository.findById(attempt.getId()).orElseThrow();
        assertThat(updatedAttempt.getStatus()).isEqualTo(AttemptStatus.RUNNING);

        // Lease is still active in database
        Integer leaseCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM execution_leases WHERE execution_public_id = ?",
                Integer.class,
                execution.getPublicId()
        );
        assertThat(leaseCount).isEqualTo(1);
    }

    @Test
    public void testSuccessfulScheduleRetry() throws Exception {
        // Setup execution in FAILED state first
        jdbcTemplate.update("UPDATE executions SET current_status = 'FAILED' WHERE public_id = ?", execution.getPublicId());

        com.flowforge.api.dto.InternalExecutionRetryRequest request = new com.flowforge.api.dto.InternalExecutionRetryRequest(
                clock.instant().plusSeconds(10),
                10L,
                "EXPONENTIAL"
        );

        mockMvc.perform(post("/internal/v1/executions/" + execution.getPublicId() + "/schedule-retry")
                        .header("X-Internal-Service-Token", "default-internal-token-secret-key-12345")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());

        // Verify Execution status is QUEUED and attempt number incremented
        Execution updatedExec = executionRepository.findByPublicId(execution.getPublicId()).orElseThrow();
        assertThat(updatedExec.getCurrentStatus()).isEqualTo(ExecutionStatus.QUEUED);
        assertThat(updatedExec.getCurrentAttemptNumber()).isEqualTo(2);
        assertThat(updatedExec.getNextAttemptAt()).isEqualTo(request.getNextAttemptAt());

        // Verify a new PENDING attempt was created
        ExecutionAttempt newAttempt = attemptRepository.findByExecutionIdAndAttemptNumber(execution.getId(), 2).orElseThrow();
        assertThat(newAttempt.getStatus()).isEqualTo(AttemptStatus.PENDING);

        // Verify outbox event version 1 created
        OutboxEvent event = outboxEventRepository.findAll().stream()
                .filter(e -> e.getEventType().equals("EXECUTION_RETRY_SCHEDULED"))
                .findFirst().orElseThrow();
        assertThat(event.getPayloadVersion()).isEqualTo(1);
        assertThat(event.getPayload()).contains("EXPONENTIAL");
    }

    @Test
    public void testScheduleRetryRejectsNonFailedState() throws Exception {
        // Execution is RUNNING (from setupData), not FAILED!
        com.flowforge.api.dto.InternalExecutionRetryRequest request = new com.flowforge.api.dto.InternalExecutionRetryRequest(
                clock.instant().plusSeconds(10),
                10L,
                "EXPONENTIAL"
        );

        mockMvc.perform(post("/internal/v1/executions/" + execution.getPublicId() + "/schedule-retry")
                        .header("X-Internal-Service-Token", "default-internal-token-secret-key-12345")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isInternalServerError()); // IllegalStateException maps to 500
    }
}
