spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dummy_test_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      auto-startup: false

flowforge:
  security:
    internal-token: default-internal-token-secret-key-12345
  result:
    api-service-url: http://localhost:8080
    topic-execution-completed: execution-completed
    group-id: result-processor-group
