spring:
  application:
    name: scheduler-service
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.time_zone: UTC

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized

flowforge:
  scheduler:
    poll-interval-ms: 1000
    batch-size: 10
    enabled: true
    max-missed-schedules-limit: 5
